//
//  MovieModel.swift
//  RottenMovies
//
//  Created by Sinklier, Nick on 3/16/21.
//

import Foundation

/// Stores movie information for populating UI.
/// - parameters:
///		- title: String for title.
///		- overview: Optional string for movie overview
///		- imageURL: Computed imageURL generated by imageURLPath.
public struct MovieModel {
	let title: String
	let overview: String?
	let voteAverage: Double?
	var imageURL: URL?
	
	init(title: String, overview: String? = nil, imageURLPath: String, voteAverage: Double? = nil) {
		self.title = title
		self.overview = overview
		self.imageURL = ImageURLFactory().makeMovieImageURL(imagePath: imageURLPath)
		self.voteAverage = voteAverage
	}
}
